version: "3.9"

services:
  api:
    build: .
    image: gallery-downloader-api:latest
    environment:
      GDL_API_TOKEN: ${GDL_API_TOKEN:-123456}
      GDL_REDIS_URL: ${GDL_REDIS_URL:-redis://redis:6379/0}
      GDL_DATABASE_URL: ${GDL_DATABASE_URL:-sqlite:///data/gallery.db}
      GDL_STORAGE_ROOT: ${GDL_STORAGE_ROOT:-/data/downloads}
      GDL_GALLERY_DL_CONFIG_PATH: /etc/gallery-dl/config.json
      GDL_GALLERY_DL_EXTRA_ARGS: ${GDL_GALLERY_DL_EXTRA_ARGS:-}
      GDL_JOB_TIMEOUT_SECONDS: ${GDL_JOB_TIMEOUT_SECONDS:-1800}
    ports:
      - "8080:8080"
    volumes:
      - gallery_data:/data
      - ${GALLERY_DL_CONFIG_PATH:-./config/gallery-dl.json}:/etc/gallery-dl/config.json:ro
    depends_on:
      - redis

  worker:
    build: .
    image: gallery-downloader-worker:latest
    entrypoint: ["python", "-m", "app.worker"]
    environment:
      GDL_API_TOKEN: ${GDL_API_TOKEN:-123456}
      GDL_REDIS_URL: ${GDL_REDIS_URL:-redis://redis:6379/0}
      GDL_DATABASE_URL: ${GDL_DATABASE_URL:-sqlite:///data/gallery.db}
      GDL_STORAGE_ROOT: ${GDL_STORAGE_ROOT:-/data/downloads}
      GDL_GALLERY_DL_CONFIG_PATH: /etc/gallery-dl/config.json
      GDL_GALLERY_DL_EXTRA_ARGS: ${GDL_GALLERY_DL_EXTRA_ARGS:-}
      GDL_JOB_TIMEOUT_SECONDS: ${GDL_JOB_TIMEOUT_SECONDS:-1800}
    volumes:
      - gallery_data:/data
      - ${GALLERY_DL_CONFIG_PATH:-./config/gallery-dl.json}:/etc/gallery-dl/config.json:ro
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  gallery_data:
  redis_data:
